### ISSUE TITLE
画面デザイン決定

### ISSUE THREAD

**Issue by Toshiki428** [HAL-OSAKA-IT/game_collect#10]
パターンA #4 とパターンB #5 を比較してどんなレイアウトにするか決定したいと思います！

皆さんの意見を聞かせてください！

![image](https://github.com/HAL-OSAKA-IT/game_collect/assets/109594862/a9b78e14-6d17-4825-8fed-defad13e43cd)

![image](https://github.com/HAL-OSAKA-IT/game_collect/assets/109594862/4a968cd0-c3a1-4868-93c3-552d3fafdce2)

比較しやすい画面を作ったので、使ってください。

画像の順で遷移するとその画面になります！

**Comment by morita-32** [comment]
私はB派です

**Comment by jmn04** [comment]
任天堂とかDeNAなどのサイトを確認した結果、作るゲームが多いならA案、そうでもないならB案といったところ。
A案は視覚情報が多くてインパクトが強い印象。
B案はテキストを含めてるから、ゲームの概要をざっと知るのに良い印象。

## A案に近い
<img width="1512" alt="任天堂" src="https://github.com/HAL-OSAKA-IT/game_collect/assets/118909709/8dcd0a88-497e-485b-8d7d-c53ccff501eb">
https://store-jp.nintendo.com/

## B案に近い
<img width="1512" alt="DeNA" src="https://github.com/HAL-OSAKA-IT/game_collect/assets/118909709/b9cab823-4bb9-4644-b057-5fa218760627">
https://dena.com/jp/services/games.html

**Comment by Toshiki428** [comment]
@jmn04 
確かにそうですね！

今回、最初に製作するゲームは3~4種類の予定なのでひとまず #5 でいきましょう。

後のアップデートでゲームが増えたときに #4 への移行を改めて考えましょう！
