### ISSUE TITLE
環境変数ファイルを作成する

### ISSUE THREAD

**Issue by Toshiki428** [HAL-OSAKA-IT/game_collect#16]
環境変数ファイルの設定をお願いします！

[環境変数についてのWiki](https://github.com/HAL-OSAKA-IT/game_collect/wiki/環境変数について)

終わったらこのIssueに返信をお願いします！

# TODO
- [ ] 最新状態をプルする
- [ ] `.env.example`をコピーする
- [ ] コピーしたファイルを`.env`に改名する
- [ ] `.env`の中身を書き換える

**Comment by morita-32** [comment]
@Toshiki428 
設定完了しました～

**Comment by jmn04** [comment]
@Toshiki428 
設定完了しました

**Comment by Toshiki428** [comment]
@morita-32 
@jmn04 
![寿司ゆき:ok](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/03.png)

**Comment by momo-717** [comment]
設定！完了しました！！！

**Comment by Toshiki428** [comment]
@momo-717 
![寿司ゆき:ok_dish](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/43.png)

**Comment by k4izu** [comment]
環境変数の
動作確認まで完了しました。

**Comment by k4izu** [comment]
誤クリックで一時閉じてしまいましたが、お気になさらずに。

**Comment by Toshiki428** [comment]
@k4izu okです！

**Comment by okinopita** [comment]
すみません！報告忘れてました！完了しました！

**Comment by Toshiki428** [comment]
@okinopita 
![寿司ゆき:yes](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/01.png)
