### ISSUE TITLE
ランキング画面の作成

### ISSUE THREAD

**Issue by Toshiki428** [HAL-OSAKA-IT/game_collect#17]
@sabuchan99 
ランキング画面の作成をお願いします。

# TODO
- [x] `ranking`ブランチの作成
- [x] `templates/ranking.php`の作成、記述
- [x] `css/ranking.scss`の作成、記述

**Comment by sabuchan99** [comment]
先ほど、rankingのブランチをプッシュしました。
確認お願いします！

**Comment by Toshiki428** [comment]
@sabuchan99 
OKです！
ざっと確認して修正してほしい部分が何点かあります！

はじめに`css/ranking.scss`これを`templates/css/ranking.scss`に変更してください！
これはこちらのミスです！すみません！

そしてscssファイルの中身ですが、まとめられるところをまとめておいて頂けると助かります！
たとえば`.table`や`.back`は`#game1_ranking_container~#game4_ranking_container`の中に記述して問題なさそうなのと、
`#game1_ranking_container~#game4_ranking_container`と`h2`の間には`#ranking_container`があった方が対応して見やすくなると思います！
また、最後に同じ記述があったりするので修正をお願いします！

もし余裕があれば、phpファイルの冗長な部分もまとめてみてください！

ここまでできたら詳しくレビューをしようと思うので**プルリクエスト**をお願いします！
