### ISSUE TITLE
環境構築

### ISSUE THREAD

**Issue by Toshiki428** [HAL-OSAKA-IT/game_collect#2]
@HAL-OSAKA-IT/game_collect_members 

15日までに全員の環境構築を完了させたいと思います！

期間が短いので急ぎでお願いします！

下記**TODO**の上2つがが完了したらここに「完了したよ」という返信をお願いします！😄

# TODO
- [x] SourceTreeをPCにインストールする（詳しくは[Wikiの環境構築](https://github.com/HAL-OSAKA-IT/game_collect/wiki/%E7%92%B0%E5%A2%83%E6%A7%8B%E7%AF%89)を確認！）
- [x] PHPで書いたコードをブラウザに表示できるようにする（こちらもWikiの環境構築にあります）
- [x] Wikiに書いているGitの操作をある程度把握しておく（こちらは余裕があればで大丈夫ですが、できるだけわかりやすくなるように努力したつもりなのでぜひ目を通してください！）

**Comment by morita-32** [comment]
完了したよ

**Comment by Toshiki428** [comment]
@morita-32 
OK！

**Comment by jmn04** [comment]
完了したよ

**Comment by Toshiki428** [comment]
@jmn04 
OK！

**Comment by okinopita** [comment]
完了したよ

**Comment by Toshiki428** [comment]
@okinopita 
OK！

**Comment by k4izu** [comment]
完了したよ

**Comment by Toshiki428** [comment]
@k4izu 
OK！

**Comment by shogo80** [comment]
完了したよ

**Comment by Toshiki428** [comment]
@shogo80 
ok！

**Comment by momo-717** [comment]
完了したよ

**Comment by Toshiki428** [comment]
@momo-717 
OK！
