### ISSUE TITLE
ゲーム企画

### ISSUE THREAD

**Issue by Toshiki428** [HAL-OSAKA-IT/game_collect#22]
24日から製作するゲームを考えてください！

今作業を進めているペアでゲーム制作までする予定です。
なので、各ペアで何を作りたいか話し合って、決まったらこのIssueでどんなゲームを作りたいか教えてください！

# TODO
- [ ] 各ペアで作りたいゲームを話し合う
- [ ] 決まったらどんなゲームを作る予定かここで共有する

**Comment by shogo80** [comment]
了解です。

**Comment by jmn04** [comment]
@Toshiki428 
23日までインターンで、玉置くんと話し合う時間を取れないので、その間どなたかに代わりをお願いしていいですか？

**Comment by Toshiki428** [comment]
@jmn04 @shogo80 

であれば、ひとまず玉置くんが作りたいと思うゲームを教えてください！
問題なさそうであれば、それで決定しましょう！

**Comment by shogo80** [comment]
タイピングゲームとかどうかな？

**Comment by Toshiki428** [comment]
@shogo80 
いいと思います！
実装時わからないところはフォローするのでそれでいきましょう！

具体的にどんなタイピングゲームにするかも考えておいてください！

**Comment by shogo80** [comment]
寿司打の英語版のようなものです。

**Comment by shogo80** [comment]
https://github.com/Siv3D/Siv3D-Samples/tree/main/Samples/SimpleOthelloAI
こういうの見つけました。

**Comment by Toshiki428** [comment]
@shogo80 
作れると面白いですが、C++で動いているみたいなので
それをCanvasに適用できるか試してみたいですね！
