### ISSUE TITLE
TOPページデザインの方針決め

### ISSUE THREAD

**Issue by Toshiki428** [HAL-OSAKA-IT/game_collect#3]
TOPページはヘッダー（ロゴ、会員機能関係）と、ゲーム一覧が表示されている画面をイメージしています。

そんなTOPページの構成案を**2パターン**作って比較したいと思います！

ゲーム一覧部分について
良さそうなレイアウトはありますか？

あればどんどん投稿してください！👍 

## TODO

- [x] #4
- [x] #5

**Comment by Toshiki428** [comment]
構成案について議論していこうと思います！

文字の入力方法は
Add a commentのところに文字を書いて
右下のcommentをクリックするだけです！

**Comment by okinopita** [comment]
ごめん！パターンAのとこ変なボタン押しちゃったけど気にしないでください！

**Comment by Toshiki428** [comment]
@okinopita 
OK！

**Comment by Toshiki428** [comment]
今のところ、グリッド状にゲーム一覧を表示するレイアウトを考えています！
イメージ的にはメルカリの商品一覧のような感じ！

他にレイアウト思いつく人いますか？

**Comment by okinopita** [comment]
特段凝る箇所でもないとは思うしそれでいいんじゃないかな

**Comment by morita-32** [comment]
![image](https://github.com/HAL-OSAKA-IT/game_collect/assets/120178967/0552799d-cffc-4bc0-8323-f820fa88099d)
![image](https://github.com/HAL-OSAKA-IT/game_collect/assets/120178967/46af5418-a95a-4693-bea8-f0a9557e622a)
![image](https://github.com/HAL-OSAKA-IT/game_collect/assets/120178967/850b8e4d-07ed-4112-bb26-ce2b0229e580)

**Comment by k4izu** [comment]
特別子供向けだったり世界観が無いのならば、現状はグリッド状で良さそうな感じがする

**Comment by Toshiki428** [comment]
森田君が送ってくれてるやつを、上部、中部、下部としたときに
イメージしてたのは中部なんだけど、これで進める？

**Comment by Toshiki428** [comment]
一応、構成案は2パターン作るつもりだから
グリッド状とこのパターンも候補に入れたいとかあれば、ぜひ教えて！

**Comment by morita-32** [comment]
画面にゲームを並べた時に、ゲームの種類の少なさのために隙間が空かないなら中部が良いと思う

**Comment by okinopita** [comment]
６個とか８個とか作れないなら縦一列でもいいのかな～とは思う

**Comment by Toshiki428** [comment]
> ６個とか８個とか作れないなら縦一列でもいいのかな～とは思う

この縦一列ってのは下部のイメージ？

**Comment by okinopita** [comment]
うん　各々の情報量としては１枚目かそれ以上ぐらいあってもいいと思う

**Comment by Toshiki428** [comment]
じゃあ

グリッド状 &rarr; パターンA
縦一列 &rarr; パターンB

で進めていきます！

**Comment by Toshiki428** [comment]
それぞれのパターンの製作をIHの人に任せたいと思ってて

- パターンAを海津くん
- パターンBを木下くん

に任せて大丈夫？

明後日ぐらいには完成させてほしい！

**Comment by morita-32** [comment]
デザインの部分かな？

**Comment by Toshiki428** [comment]
あ、確かに伝え方が悪かった

そう！デザイン！

**Comment by k4izu** [comment]
何で作って欲しいとかはある感じ？HTMLが良いとか、Figmaの方が好ましいみたいな

**Comment by Toshiki428** [comment]
作りやすいもので大丈夫だけど共有は画像でしてほしい！

**Comment by okinopita** [comment]
分かった！環境構築から取り掛かるけど何かほかに話すことはある？

**Comment by Toshiki428** [comment]
今回はデザインの方針と担当を決めたかっただけだからこれで大丈夫かな！

他に何かある人がいなければ

**Comment by Toshiki428** [comment]
じゃあこのissueを閉じます！

パターンAとパターンBのissueを作成しておくので、デザインが完成した時はそっちに投稿してください！
