### ISSUE TITLE
パターンA：グリッドレイアウトバージョン

### ISSUE THREAD

**Issue by okinopita** [HAL-OSAKA-IT/game_collect#4]
今回製作するTOPページのデザイン。

**Comment by k4izu** [comment]
![grid_a](https://github.com/HAL-OSAKA-IT/game_collect/assets/150760832/2c8c95da-7d46-448a-afb9-dabc79e40b69)

簡易的なものですが、このような形で大丈夫ですか？

**Comment by Toshiki428** [comment]
ありがとうございます！ @k4izu 

一点修正してほしいところがあって
headerを除いたmainの部分は、横幅を80%ほどにして中央寄せにしてみてほしいです！

**Comment by k4izu** [comment]
![grid_al](https://github.com/HAL-OSAKA-IT/game_collect/assets/150760832/9b1c40e3-4cab-435a-9d8a-9a6da0e700b7)

修正版です。

**Comment by Toshiki428** [comment]
ありがとうございます！

パターンAはこのレイアウトで決定します。

このコメントが確認出来たらこのissueのcloseをお願いします！ @k4izu

**Comment by k4izu** [comment]
確認しました。
