### ISSUE TITLE
パターンB：シングルカラムレイアウトバージョン

### ISSUE THREAD

**Issue by Toshiki428** [HAL-OSAKA-IT/game_collect#5]
今回製作するTOPページのデザイン。

**Comment by okinopita** [comment]
![スクリーンショット 2023-12-13 191359](https://github.com/HAL-OSAKA-IT/game_collect/assets/114094511/a799a9b0-ff24-468a-b8cd-a53b64753a2a)
遅くなってごめんなさい！こんな感じでどうでしょうか(上部のxマークは気にしないでください)

**Comment by Toshiki428** [comment]
@okinopita 
ありがとうございます！

パターンBはこれでいきましょう！
