### ISSUE TITLE
データベース作成

### ISSUE THREAD

**Issue by Toshiki428** [HAL-OSAKA-IT/game_collect#8]
画面設計と同時並行でデータベース作成に取り掛かります！

データベース設計をしたいという人はいますか？

いたらその人に任せて、いなければこちらで指名します！

**Comment by jmn04** [comment]
DB設計やらせてください。

**Comment by Toshiki428** [comment]
@jmn04 
OKです！

門脇君がやってくれるのであれば、設計は基本的にお任せしようと思います！

- データベース名：`game_collect`
- テーブル名：お任せします

以下の機能に必要なテーブルを設計してください。
- 会員がニックネームとパスワードを用いてログインできる
- 作ったアカウントは削除することができる
- 会員のゲームごとのスコアを記録、表示できる

今回はメールアドレス登録など必要ないので、上記の機能を満たせば大丈夫なはずです！


設計とテーブルのCREATE文作成までお願いします！

画面デザイン完成と同時に終わらせたいので、明後日までに完成でいけそうですか？

**Comment by jmn04** [comment]
@Toshiki428 
設計要件確認しました。
本日中に論理モデルの共有まで行い、明後日までに所定の作業を完了させます。

**Comment by jmn04** [comment]
以下の内容で設計しました。
パスワードはセキュリティの観点から、ハッシュ化したパスワードの登録を想定しています。
ユーザー情報の変更も想定して変更日時を記載しています。
問題ないか確認お願いします。

<img width="640" alt="db_design" src="https://github.com/HAL-OSAKA-IT/game_collect/assets/118909709/da12c7df-93e5-4723-a748-92dcde27ce23">

**Comment by jmn04** [comment]
@Toshiki428 
以下の内容で設計しました。

- パスワードはセキュリティの観点から、ハッシュ後のパスワード保存を想定。
- 会員情報を変更する可能性を鑑み、変更日時を追加。

問題ないか確認お願いします

<img width="640" alt="db_design" src="https://github.com/HAL-OSAKA-IT/game_collect/assets/118909709/4e30b560-cbf6-48f4-84fd-3d4927ae0e5b">

**Comment by Toshiki428** [comment]
@jmn04 
ありがとうございます！

2点気になるところがあったので共有します。

- 削除済みフラグは削除日時にして退会日時を保存して置けるような設計がいいと思います。
- ゲームごとのスコアを記録したいので、ゲームテーブルを作って、スコアテーブルにもう一つ外部キーを持たせてください！

確認、修正お願いします！

**Comment by jmn04** [comment]
指摘内容確認の上、修正したので確認お願いします。

<img width="640" alt="db_design2" src="https://github.com/HAL-OSAKA-IT/game_collect/assets/118909709/346672cd-4de2-469f-938b-794c66d6afff">

**Comment by Toshiki428** [comment]
削除日時のNOT NULLを修正すれば、問題ないと思います！

ここは実装時に修正で大丈夫なので、これで進めましょう！

**Comment by jmn04** [comment]
ER図にも誤りがあったので修正版を添付しておきます！

<img width="640" alt="db_design_fixed" src="https://github.com/HAL-OSAKA-IT/game_collect/assets/118909709/5bad0759-8035-470e-af73-69565706aff0">

**Comment by jmn04** [comment]
# game_collectのCREATE文

### game_collectデータベース
```
CREATE DATABASE IF NOT EXISTS `game_collect` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `game_collect`;
```

### gamesテーブル
```
CREATE TABLE IF NOT EXISTS `games` (
  `id` int(2) NOT NULL AUTO_INCREMENT COMMENT 'ゲームID',
  `name` varchar(30) NOT NULL COMMENT 'ゲーム名',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日時',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```
### membersテーブル
```
CREATE TABLE IF NOT EXISTS `members` (
  `id` int(5) NOT NULL AUTO_INCREMENT COMMENT 'ユーザーID',
  `name` varchar(15) NOT NULL COMMENT 'ユーザー名',
  `password` varchar(100) NOT NULL COMMENT 'パスワード',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日時',
  `updated_at` datetime DEFAULT NULL COMMENT '更新日時',
  `deleted_at` datetime DEFAULT NULL COMMENT '削除日時',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

### scoresテーブル
```
CREATE TABLE IF NOT EXISTS `scores` (
  `id` int(8) NOT NULL AUTO_INCREMENT COMMENT 'スコアID',
  `game_id` int(2) NOT NULL COMMENT 'ゲームID',
  `user_id` int(5) NOT NULL COMMENT 'ユーザーID',
  `score` int(8) NOT NULL COMMENT 'スコア',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日時',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_scores_game` FOREIGN KEY (`game_id`) REFERENCES `games` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_scores_member` FOREIGN KEY (`user_id`) REFERENCES `members` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

**Comment by jmn04** [comment]
<img width="640" alt="designer" src="https://github.com/HAL-OSAKA-IT/game_collect/assets/118909709/43a53ec2-2bdd-4f92-b35e-4bbfabc66c61">

**Comment by Toshiki428** [comment]
@jmn04 
確認できました！

このSQL文をまとめた`.sql`ファイルを、リポジトリに追加してプルリクエストを出すところまでお願いします！

**Comment by jmn04** [comment]
@Toshiki428 
databaseブランチを作成し、プルリクしました。
