### ISSUE TITLE
ロゴ画像の作成

### ISSUE THREAD

**Issue by Toshiki428** [HAL-OSAKA-IT/game_collect#9]
@shogo80 

製作するサイトのロゴを作ろうと思います！

ロゴ製作は玉置くんにお任せしようと思うのですが、大丈夫ですか？

明後日までにロゴの完成させてほしいです！

- [Wix](https://ja.wix.com/logo/maker)

こういうサイトを使うと楽に作れます！

**Comment by shogo80** [comment]
了解です。
